// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icpixgdslmbcoicqtjwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcGl4Z2RzbG1iY29pY3F0and5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDM1MTIsImV4cCI6MjA2ODg3OTUxMn0.h2hzKjjpsCPNf-y0Vkyz5zAPhiDwjavcSfnMwnXN_2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});